"""Windows versions database with official download info."""

WINDOWS_VERSIONS = [
    {
        "id": "win11_pro",
        "name": "Windows 11 Pro",
        "version": "24H2",
        "build": "26100",
        "size_gb": 5.8,
        "recommended": True,
        "features": ["TPM 2.0 ready", "BitLocker", "Remote Desktop", "Hyper-V"],
        "color": "#0078d4",
        "download_url": "https://www.microsoft.com/software-download/windows11",
        "arch": "x64",
    },
    {
        "id": "win11_home",
        "name": "Windows 11 Home",
        "version": "24H2",
        "build": "26100",
        "size_gb": 5.6,
        "recommended": False,
        "features": ["Modern UI", "Microsoft Store", "Xbox integration", "Teams"],
        "color": "#0078d4",
        "download_url": "https://www.microsoft.com/software-download/windows11",
        "arch": "x64",
    },
    {
        "id": "win10_pro",
        "name": "Windows 10 Pro",
        "version": "22H2",
        "build": "19045",
        "size_gb": 4.9,
        "recommended": False,
        "features": ["Stable", "No TPM required", "BitLocker", "Group Policy"],
        "color": "#00adef",
        "download_url": "https://www.microsoft.com/software-download/windows10",
        "arch": "x64",
    },
    {
        "id": "win10_home",
        "name": "Windows 10 Home",
        "version": "22H2",
        "build": "19045",
        "size_gb": 4.7,
        "recommended": False,
        "features": ["Stable", "No TPM required", "Lightweight", "Wide compatibility"],
        "color": "#00adef",
        "download_url": "https://www.microsoft.com/software-download/windows10",
        "arch": "x64",
    },
    {
        "id": "win11_ltsc",
        "name": "Windows 11 LTSC",
        "version": "2024",
        "build": "26100",
        "size_gb": 4.2,
        "recommended": False,
        "features": ["No bloatware", "Long-term support", "Minimal", "Corporate"],
        "color": "#5c2d91",
        "download_url": "https://www.microsoft.com/evalcenter/evaluate-windows-11-enterprise",
        "arch": "x64",
    },
]

BYPASS_OPTIONS = [
    {
        "id": "bypass_tpm",
        "name": "Обход TPM 2.0",
        "description": "Позволяет установить Windows 11 без модуля TPM 2.0",
        "registry_key": "HKLM\\SYSTEM\\Setup\\LabConfig",
        "registry_value": "BypassTPMCheck",
        "default": True,
    },
    {
        "id": "bypass_secureboot",
        "name": "Обход Secure Boot",
        "description": "Установка на системах без Secure Boot",
        "registry_key": "HKLM\\SYSTEM\\Setup\\LabConfig",
        "registry_value": "BypassSecureBootCheck",
        "default": True,
    },
    {
        "id": "bypass_ram",
        "name": "Обход проверки RAM",
        "description": "Установка на системах с менее 4 ГБ ОЗУ",
        "registry_key": "HKLM\\SYSTEM\\Setup\\LabConfig",
        "registry_value": "BypassRAMCheck",
        "default": False,
    },
    {
        "id": "bypass_storage",
        "name": "Обход проверки диска",
        "description": "Установка на диск менее 64 ГБ",
        "registry_key": "HKLM\\SYSTEM\\Setup\\LabConfig",
        "registry_value": "BypassStorageCheck",
        "default": False,
    },
]
